server:
  port: 8081

spring:
  application:
    name: user-service
  datasourc: 
    url: jdbc:h2:mem:userDB
    driverClassName: org.h2.Driver
    username: sa
    password: password

spring:
  jpa:  
    show_sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console